# API Gateway - dev ortami: tum altyapi lokalde (podman compose) calisir.

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

discovery:
  dashboard-url: http://localhost:8761

keycloak:
  issuer-uri: http://localhost:8180/realms/crm
  client-id: crm-client
  client-secret: crm-client-secret

# Angular dev server (ng serve) buradan istek atar.
cors:
  allowed-origins: http://localhost:4200

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
