# contact-info-service - test ortami.

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/crm}

eureka:
  instance:
    prefer-ip-address: true
